// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIesgtDcwW11FnCq8p1xgpldvAKztOK7s',
    appId: '1:155290127830:web:6583da14e3fa9105ab2877',
    messagingSenderId: '155290127830',
    projectId: 'asd-ml',
    authDomain: 'asd-ml.firebaseapp.com',
    storageBucket: 'asd-ml.appspot.com',
    measurementId: 'G-SS4BNXP7NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhyT8FH7HDsK-CgEIHfK8AJPD7onu-zc',
    appId: '1:155290127830:android:ff25f770d426c567ab2877',
    messagingSenderId: '155290127830',
    projectId: 'asd-ml',
    storageBucket: 'asd-ml.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqZvUVgbCmA7AKwDVez_6iQU-5DJaqZ8',
    appId: '1:155290127830:ios:d6928edf3b823173ab2877',
    messagingSenderId: '155290127830',
    projectId: 'asd-ml',
    storageBucket: 'asd-ml.appspot.com',
    iosBundleId: 'com.example.asd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqZvUVgbCmA7AKwDVez_6iQU-5DJaqZ8',
    appId: '1:155290127830:ios:a13d2357d8dcff92ab2877',
    messagingSenderId: '155290127830',
    projectId: 'asd-ml',
    storageBucket: 'asd-ml.appspot.com',
    iosBundleId: 'com.example.asd.RunnerTests',
  );
}
